import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { T, useSetLanguage, useCurrentLanguage } from '@tolgee/react';

export default function Home() {
  const setLanguage = useSetLanguage();
  const getLanguage = useCurrentLanguage();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <T keyName='welcome' /> <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <div className={styles.description}>
          <T keyName='description'>Get started by editing </T>{' '}
          <code className={styles.code}>pages/index.js</code>
          <p>
            <T keyName='translate-paragraph'>Translate page</T>
          </p>
          <select
            className={styles.select}
            onChange={(e) => setLanguage(e.target.value)}
            value={getLanguage()}
          >
            <option value='en'>English</option>
            <option value='es-es'>Spanish (España)</option>
            <option value='fr-pf'>French (Polynésie française)</option>
            <option value='hi-IN'>Hindi (भारत)</option>
            <option value='it-IT'>Italian (italia)</option>
            <option value='zh'>Chinese - simplified (中文)</option>
          </select>
        </div>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>
              <T keyName='list1-title'>Documentation</T> &rarr;
            </h2>
            <p>
              <T keyName='list1-body'>
                Find in-depth information about Next.js features and API.
              </T>
            </p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>
              {' '}
              <T keyName='list2-title'>Learn</T> &rarr;
            </h2>
            <p>
              <T keyName='list2-body'>
                Learn about Next.js in an interactive course with quizzes!
              </T>
            </p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}
          >
            <h2>
              <T keyName='list3-title'>Examples </T>&rarr;
            </h2>
            <p>
              <T keyName='list3-body'>
                Discover and deploy boilerplate example Next.js projects.
              </T>
            </p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>
              <T keyName='list4-title'>Deploy</T> &rarr;
            </h2>
            <p>
              <T keyName='list4-body'>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </T>
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          <T keyName='footer'>Powered by</T>{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
